name = "thesurvivorgods"
main = "./src/server.js"
compatibility_date="2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
